name: "Deploy Posetrix"

on:
  # push:
  #   tags:
  #     - 'v*'   # Trigger on semantic version tags
  # release:
  #   types:
  #     - created  # Trigger on new releases
    workflow_dispatch:
env:
    PROJECT_PATH: Posetrix/Posetrix.csproj
jobs:
    build:
        runs-on: windows-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            
            - name: Set up NET
              uses: actions/setup-dotnet@v4
              with:
                dotnet-version: '9.0.x'

            - name: Restore dependencies
              run: dotnet restore

            - name: Build project
              run: dotnet build -c Release -o ./output

            - name: Publish project
              run: dotnet publish -c Release --self-contained -r win-x64 -p:PublishSingleFile=true

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: Posetrix-SelfContained
                path: ./output

    